import { cn } from '@/lib/utils'
import './globals.css'
import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'

const rubikFont = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(rubikFont.className, 'bg-gray-950 text-white')}>{children}</body>
    </html>
  )
}
