import { cn } from '@/lib/utils';
import './globals.css';
import type { Metadata } from 'next';
import { Rubik } from 'next/font/google';
import { Analytics } from '@vercel/analytics/react';

const rubikFont = Rubik({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          rubikFont.className,
          'flex min-h-screen flex-col bg-gray-950 text-white'
        )}
      >
        {children}
        <Analytics />
      </body>
    </html>
  );
}
